- doc/ltac2.md
Feeling at reading it: a very impressive work, need time to digest all the contents.
> Typos found while reading ltac2.md

- src/g_ltac2.ml4
See https://github.com/coq/coq/pull/6197
> [coq] Adapt to Coq's new functional EXTEND API.

- src/tac2core.ml
- src/tac2match.ml
To merge at the same time as coq/coq#6169.
> Adapt to removal of match_appsubterm.

- _CoqProject
- src/g_ltac2.ml4
- src/tac2core.ml
- src/tac2tactics.ml
Overlay for coq/coq#6493 (to be merged after #6493 is merged in Coq)
> adapt to API.mli removal

- src/tac2intern.ml
- src/tac2qexpr.mli
- src/tac2quote.ml
- src/tac2tactics.ml
> [coq] Adapt to coq/coq#6745

- src/tac2stdlib.ml
- src/tac2tactics.ml
- src/tac2tactics.mli
Minor, a couple of tactic-related types moved.
> [coq] Adapt to coq/coq#6960.

- src/tac2stdlib.ml
c.f. https://github.com/coq/coq/pull/7196
> Adapt to fix/cofix changes in Coq (coq/coq#7196)

- src/tac2entries.ml
- src/tac2ffi.mli
- src/tac2intern.ml
- src/tac2quote.mli
- src/tac2tactics.mli
@ppedrot, in case you're interested in them.
> Adapt to renamings done in Coq PRs 7177  and 6156

- src/g_ltac2.ml4
Trivial renaming of the vernacular parsing entry point.
> Adapt to coq/coq#7558.

- .travis.yml
Pretty straightforward; need to be enabled in the Travis console tho.
> [ci] Add travis setup, docker-based.

- src/g_ltac2.mlg
To be merged when the Coq developers merge the PR upstream.
> [coq] Overlay to adapt to coq/coq#9003

- src/g_ltac2.mlg
> Fix w.r.t. coq/coq#9051.

- src/g_ltac2.mlg
- src/tac2core.ml
- src/tac2entries.ml
Note that this highlights some issues with the current Coq interface,
not clear what should we do.
> [coq] Adapt to coq/coq#9172

- src/g_ltac2.mlg
To be merged once https://github.com/coq/coq/pull/9263 is.
> Adapt to Coq's new proof mode API

- src/tac2core.ml
- src/tac2tactics.ml
This is to be merged only after https://github.com/coq/coq/pull/9410 is merged.
> Adapt to https://github.com/coq/coq/pull/9410

- src/dune
- src/tac2tactics.ml
To be merged when the upstream PR is merged.
Not sure this is the right thing to do tho.
> [coq] Adapt to coq/coq#9173

- src/g_ltac2.mlg
- src/tac2core.ml
- src/tac2entries.ml
- src/tac2env.ml
- src/tac2ffi.ml
- src/tac2intern.ml
- src/tac2interp.ml
- src/tac2match.mli
- src/tac2print.ml
- src/tac2quote.ml
In anticipation to https://github.com/coq/coq/pull/9605 , we fix all
OCaml warnings.
Fixes #107
> [coq] Fix OCaml warnings.

- src/tac2core.ml
> Adapt to coq/coq#8817 (SProp)

- src/tac2core.ml
To be merged only once coq/coq#9678 is.
> Adapt to changes in Coq's printers API

- .gitignore
- dune
- dune-project
- src/dune
- theories/dune
This add experimental support for building the full Ltac2 plugin with Dune, see tree at https://github.com/ejgallego/dune/tree/coq
> [dune] Full Dune support.

- src/tac2tactics.ml
> Fix for https://github.com/coq/coq/pull/8984

- src/tac2core.ml
To be merged only once https://github.com/coq/coq/pull/9909 is.
> Adapt to Coq's PR #9909
